spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/blog?characterEncoding=UTF-8
        username: root
        password: smongs1102
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: update
            # naming:
            #     physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            # use-new-id-generator-mapping: false
        properties:
            hibernate.format_sql: true
        # show-sql: true
    # profiles:
    #     include: security
    main:
        allow-bean-definition-overriding: true